### ISSUE TITLE
This week - milestone 3

### ISSUE THREAD

**Issue by zoepan00** [UBC-MDS/DSCI_522_group-314#39]
- [x] makefile @zoepan00 

Issues and feedback:
- [x] #35 Scripts add test, documentations @elliott-ribner @zoepan00 
- [x] #35 Analysis scripts documentation @dataubc 
- [x] #36 label confusion matrix, combine and label evaluation matrix table @elliott-ribner @dataubc 
- [x] #36 figure 4 and figure 2 @zoepan00 
- [x] #37 @zoepan00 @dataubc 
- [x] #38 explain precision/recall @zoepan00
